config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy] do
      resources :likes, only: [:index, :create, :new]
      resources :comments, only: [:index, :create, :new, :destroy]
    end
  end
  namespace :api do
    namespace :v1 do
      get "users/:id", to: "users#user_posts"
      get "users/:id/:post_id", to: "users#post_comments"
      post "users/:id/:post_id", to: "users#create_comments"
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all if user.role == 'admin'

    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  belongs_to :post

  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  belongs_to :post

  after_save :update_like_counter

  def update_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_posts_counter

  def update_posts_counter
    user.increment!(:posts_counter)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attr_accessor :posts_counters

  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  # validates :name, presence: true
  # validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    @recent_posts = posts.all.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/api_controller.rb
module Api
  module V1
    class ApiController < ApplicationController
      protect_from_forgery with: :null_session
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApiController
      skip_before_action :authenticate_user!
      def user_posts
        user = User.find(params[:id])
        result = user.posts
        render json: { message: 'success', posts: result }
      end

      def post_comments
        post = Post.find_by(id: params[:post_id])
        render json: { message: 'success', comments: post.comments }
      end

      def create_comments
        @comment = Comment.new(text: params[:text])
        @comment.author_id = params[:id]
        @comment.post = Post.find(params[:post_id])
        if @comment.save
          render json: { status: 'Success', data: @comment }
        else
          render json: { status: 'Failure', error: @comment.errors.full_messages }
        end
      end
    end
  end
end

app/controllers/api/v1_controller.rb
class Api::V1Controller < ApplicationController
  def users; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.post = Post.find(params[:post_id])
    @comment.author_id = current_user.id
    redirect_to user_post_path(id: @comment.post_id) if @comment.save
  end

  def destroy
    @comment = Comment.find(params[:id])
    if current_user.admin? || current_user.id == @comment.author_id
      @comment.destroy
      flash[:success] = 'Comment deleted successfully.'
    else
      flash[:error] = 'You are not authorized to delete this comment.'
    end
    redirect_to user_post_path(@user, params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    puts params[:post_id]
    @like = Like.new(author_id: params[:author_id], post: Post.find(params[:post_id]))
    redirect_to user_post_path(id: params[:author_id], post_id: params[:post_id]) if @like.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource only: [:destroy]

  def index
    @user = User.includes(:posts).find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @like_user = User.first
    @comments = @post.comments.includes(:user)
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.likes_counter = 0
    @post.comments_counter = 0
    return unless @post.save

    redirect_to user_posts_path
  end

  def new
    @post = Post.new
  end

  def create_comment
    @comment = Comment.new(comment_params)
    @comment.post = Post.find(params[:id])
    @comment.author_id = current_user.id
    redirect_to user_post_path if @comment.save
  end

  def destroy
    Post.delete(params[:id])
    redirect_to user_posts_path
  end

  def create_like
    @like = Like.new(author_id: current_user.id, post: Post.find(params[:id]))
    redirect_to user_post_path if @like.save
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="singlePost">
  <div class="postTitle">
    <h3>Post #<%= post.id %></h3>
    <p><%= post.text %></p>
  </div>
  <div class="counterSection">
    <span>Comments: <%= post.comments_counter %></span>
    <span>Likes: <%= post.likes_counter %></span>
  </div>
</div>

app/views/posts/_user_post.html.erb
<div class="userPostDiv">
  <div class = 'userPostTopDiv'>
    <h4> <%= post.title %> by <%= post.user.name %> </h4>
    <aside>
      <span>Comments: <%= post.comments_counter %></span>
      <span>Likes: <%= post.likes_counter %></span>
    </aside>
  </div>
  <%if can? :destroy, @post%>
    <%= button_to "Delete A Post", user_post_path(@post.author_id, @post.id), method: :delete, data: {turbo: false}%>
  <%end%>
  <% puts "*******************************************"%>
  <% puts @like_user%>
  <% puts "**************************************"%>
  <p><%= post.text %></p>
  <%= form_with model: @like, url: user_post_likes_path(author_id: @like_user.id, post_id: post.id), method: :post do |f| %>
    <%= f.submit "Like" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="post-section">
  <% content_for :title, "#{@user.name}'s Posts" %>
  <%= render "users/user", user: @user %>
  <% @user.posts.each do | post | %>
    <%= link_to user_post_path(@user, post) do %>
      <%= render "post", post: post %>

      <div>
        <h4>
          <span>Comments</span>
          <span>for Post: </span>
          <span><%="#{post.title}"%> </span>
        </h4>
        <div class='postComments'>
          <% post.recent_comments.each do |comment| %>
            <div>
              <p>
                <span><strong><%= comment.user.name%>:</strong></span>
                <span><%= comment.text %></span>
              </p>
            </div>
            <%if can? :destroy, comment%>
            <%= button_to "Delete Comment", user_post_comment_path(@user, post, comment), method: :delete, data: { turbo: false } %>
            <%end%>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="post-container">
  <h1>Create New Post</h1>

  <%= form_with model: @post, url: user_posts_path, method: :post, scope: :post do |f| %>
    <div class="inputs">
      <%= f.text_field :title, placeholder: 'Post Title' %>
      <%= f.text_area :text, placeholder: 'Details' %>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<% content_for :title, "#{@user.name} | #{@post.title}" %>
<div class="mainContainer">
<%= render "user_post", post: @post%>
<p> <%= @user.posts_counters%> </p>
<div class="commentsDiv">
  <% @comments.each do |comment| %>
    <div >
      <p>
        <span><strong><%= comment.user.name %>:</strong></span>
        <span><%= comment.text %></span>
      </p>
    </div>
  <% end %>
  </div>

  <%= form_with model: @comment, url: user_post_comments_path(post_id: @post.id), method: :post, scope: :comment do |f| %>
    <div>
      <%= f.text_area :text, placeholder: "Add Comment" %>
      <%= f.submit "Comment" %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<%= link_to user_path(user) do %>
  <div class="userCard">
    <div class="userCardRight">
      <h3 class="username"><%= user.name %></h3>
      <span class="post-counter">Number of posts: <%= user.posts_counter %></span>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<% content_for :title, "Blog App" %>
<section class="usersContainer">
  <% @user.each do |user| %>
    <%= render "user", user: user %>
  <% end %>
</section>

app/views/users/show.html.erb
<% content_for :title, "#{@user.name}' Blog" %>
<section class="userDetailsSection">
  <%= render "user", user: @user, like_user: @like_user %>
  <div class="bio">
    <h3>Bio</h3>
      <p class='bioDesc'><%= @user.bio %></p>
  </div>
  <br>
  <%= link_to  new_user_post_path(@user) do %>
    <button type="button" class="seeAllPosts">Create Post</button>
  <% end %>
  <div class='recentPosts'>
    <% @user.recent_posts.each do |post| %>
      <%= link_to user_post_path(@user, post) do %>
        <%= render "posts/post", post: post %>
      <% end %>
    <% end %>
  </div>
  <%= link_to user_posts_path(@user) do %>
    <button type="button" class="seeAllPosts">See all posts</button>
  <% end %>
</section>